{% set python_min = '3.10' %}
{% set name = "bokeh_sampledata" %}
{% set version = "2024.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bokeh_sampledata-{{ version }}.tar.gz
  sha256: e63daa96e79d563ec8b84f20672ffe94f905b21455fab8d83ee334e46da33624

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=69.5.1
    - setuptools-git-versioning
    - pip
  run:
    - python >={{ python_min }}
    - icalendar
    - pandas >=1.2

test:
  imports:
    - bokeh_sampledata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Sample datasets for Bokeh examples
  license: BSD-3-Clause
  license_file: LICENSE.txt
  home: https://bokeh.org/

extra:
  recipe-maintainers:
    - hoxbro
